<?php

namespace Database\Seeders;

use App\Models\CuratedRepo;
use Illuminate\Database\Seeder;

class CuratedRepoSeeder extends Seeder
{
    public function run(): void
    {
        $repos = [
            [
                'title'       => 'modelcontextprotocol/servers',
                'url'         => 'https://github.com/modelcontextprotocol/servers',
                'description' => 'Reference implementations for Model Context Protocol (MCP) servers (Postgres, SQLite, Git, Filesystem, Slack).',
                'category'    => 'MCP & Tooling',
                'tags'        => ['mcp', 'protocol', 'python', 'typescript'],
                'why_great'   => 'The definitive gold standard for how LLM agents interact with local databases, system tools, and APIs cleanly without messy custom glue code.',
                'stars'       => 18500,
                'featured'    => true,
                'sort_order'  => 1,
            ],
            [
                'title'       => 'anthropics/anthropic-sdk-python',
                'url'         => 'https://github.com/anthropics/anthropic-sdk-python',
                'description' => 'Official Python client library for Anthropic Claude models, tools, and batch processing.',
                'category'    => 'LLM SDKs',
                'tags'        => ['claude', 'python', 'ai-agents'],
                'why_great'   => 'Remarkably clean async client with native prompt caching and tool-use support that outperforms raw HTTP requests in production.',
                'stars'       => 4200,
                'featured'    => true,
                'sort_order'  => 2,
            ],
            [
                'title'       => 'google-gemini/generative-ai-python',
                'url'         => 'https://github.com/google-gemini/generative-ai-python',
                'description' => 'Official Python SDK for the Google Gemini API, structured outputs, and multimodality.',
                'category'    => 'LLM SDKs',
                'tags'        => ['gemini', 'google', 'multimodal'],
                'why_great'   => 'Massive context windows (up to 2M tokens) and native image/audio understanding make this essential for deep analysis agents.',
                'stars'       => 5800,
                'featured'    => true,
                'sort_order'  => 3,
            ],
            [
                'title'       => 'vllm-project/vllm',
                'url'         => 'https://github.com/vllm-project/vllm',
                'description' => 'A high-throughput and memory-efficient inference and serving engine for LLMs using PagedAttention.',
                'category'    => 'Inference & Serving',
                'tags'        => ['vllm', 'inference', 'cuda', 'paged-attention'],
                'why_great'   => 'The backbone of self-hosted open LLM deployments. 2-4x higher throughput than HuggingFace TGI.',
                'stars'       => 36000,
                'featured'    => true,
                'sort_order'  => 4,
            ],
            [
                'title'       => 'langchain-ai/langgraph',
                'url'         => 'https://github.com/langchain-ai/langgraph',
                'description' => 'Build resilient language agents as graphs with cyclical loops, human-in-the-loop, and persistence.',
                'category'    => 'Agent Frameworks',
                'tags'        => ['agents', 'graph', 'langchain', 'state-machine'],
                'why_great'   => 'Provides state-machine determinism to AI agent loops instead of leaving multi-step workflows to random chance.',
                'stars'       => 12500,
                'featured'    => true,
                'sort_order'  => 5,
            ],
            [
                'title'       => 'crewAIInc/crewAI',
                'url'         => 'https://github.com/crewAIInc/crewAI',
                'description' => 'Framework for orchestrating role-playing, autonomous AI agents for collaborative intelligence.',
                'category'    => 'Agent Frameworks',
                'tags'        => ['multi-agent', 'orchestration', 'python'],
                'why_great'   => 'Intuitive role-based mental model (Researcher, Writer, Auditor) that makes complex multi-agent swarms easy to conceptualize.',
                'stars'       => 24000,
                'featured'    => false,
                'sort_order'  => 6,
            ],
            [
                'title'       => 'microsoft/autogen',
                'url'         => 'https://github.com/microsoft/autogen',
                'description' => 'A framework for building multi-agent conversational systems and group chat dynamics.',
                'category'    => 'Agent Frameworks',
                'tags'        => ['microsoft', 'autogen', 'multi-agent'],
                'why_great'   => 'Groundbreaking architecture for autonomous agent-to-agent code generation and execution loops.',
                'stars'       => 35000,
                'featured'    => false,
                'sort_order'  => 7,
            ],
            [
                'title'       => 'run-llama/llama_index',
                'url'         => 'https://github.com/run-llama/llama_index',
                'description' => 'Context augmentation framework for LLM applications with advanced RAG indexing and retrieval.',
                'category'    => 'RAG & Vector Search',
                'tags'        => ['rag', 'embeddings', 'vector-db', 'llama-index'],
                'why_great'   => 'Best-in-class data connectors for PDFs, Notion, SQL, and enterprise data with hybrid retrieval.',
                'stars'       => 39000,
                'featured'    => true,
                'sort_order'  => 8,
            ],
            [
                'title'       => 'qdrant/qdrant',
                'url'         => 'https://github.com/qdrant/qdrant',
                'description' => 'High-performance vector similarity search engine with extended filtering support in Rust.',
                'category'    => 'RAG & Vector Search',
                'tags'        => ['rust', 'vector-db', 'similarity-search'],
                'why_great'   => 'Blazing fast vector lookup with rich metadata payload filtering, written in Rust with minimal memory footprint.',
                'stars'       => 22000,
                'featured'    => false,
                'sort_order'  => 9,
            ],
            [
                'title'       => 'chroma-core/chroma',
                'url'         => 'https://github.com/chroma-core/chroma',
                'description' => 'The AI-native open-source embedding database for rapid prototyping and local vector search.',
                'category'    => 'RAG & Vector Search',
                'tags'        => ['embeddings', 'python', 'vector-search'],
                'why_great'   => 'Zero-setup embedded database that lets you spin up local vector search in 3 lines of Python.',
                'stars'       => 16500,
                'featured'    => false,
                'sort_order'  => 10,
            ],
            [
                'title'       => 'remotion-dev/remotion',
                'url'         => 'https://github.com/remotion-dev/remotion',
                'description' => 'Make programmatic videos with React and CSS motion design.',
                'category'    => 'Video & Media',
                'tags'        => ['video', 'react', 'motion-graphics', 'typescript'],
                'why_great'   => 'Programmatic video rendering engine that turns React components into frame-accurate 60fps MP4 reels.',
                'stars'       => 21000,
                'featured'    => true,
                'sort_order'  => 11,
            ],
            [
                'title'       => 'openai/whisper',
                'url'         => 'https://github.com/openai/whisper',
                'description' => 'Robust Speech Recognition via Large-Scale Weak Supervision.',
                'category'    => 'Video & Media',
                'tags'        => ['speech-to-text', 'audio', 'transcription'],
                'why_great'   => 'State-of-the-art multilingual audio transcription that forms the backbone of all video subtitle pipelines.',
                'stars'       => 72000,
                'featured'    => false,
                'sort_order'  => 12,
            ],
            [
                'title'       => 'AUTOMATIC1111/stable-diffusion-webui',
                'url'         => 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
                'description' => 'Stable Diffusion web UI for image synthesis, ControlNet, and LoRA experimentation.',
                'category'    => 'Video & Media',
                'tags'        => ['diffusion', 'generative-ai', 'image-gen'],
                'why_great'   => 'The open powerhouse for generative visual pipelines, ControlNet pose locking, and localized inpainting.',
                'stars'       => 145000,
                'featured'    => false,
                'sort_order'  => 13,
            ],
            [
                'title'       => 'n8n-io/n8n',
                'url'         => 'https://github.com/n8n-io/n8n',
                'description' => 'Fair-code workflow automation platform with native AI agent nodes and LangChain integrations.',
                'category'    => 'Automation',
                'tags'        => ['automation', 'workflow', 'ai-nodes', 'typescript'],
                'why_great'   => 'Visual workflow canvas with full self-hosting control and native AI agent routing.',
                'stars'       => 56000,
                'featured'    => true,
                'sort_order'  => 14,
            ],
            [
                'title'       => 'activepieces/activepieces',
                'url'         => 'https://github.com/activepieces/activepieces',
                'description' => 'Open source business automation tool and Zapier alternative with TypeScript-first pieces.',
                'category'    => 'Automation',
                'tags'        => ['automation', 'typescript', 'open-source'],
                'why_great'   => 'Clean TypeScript piece architecture makes writing custom integrations and internal API connectors effortless.',
                'stars'       => 12000,
                'featured'    => false,
                'sort_order'  => 15,
            ],
            [
                'title'       => 'ollama/ollama',
                'url'         => 'https://github.com/ollama/ollama',
                'description' => 'Get up and running with Llama 3, Mistral, and other large language models locally.',
                'category'    => 'Inference & Serving',
                'tags'        => ['local-llm', 'go', 'llama3'],
                'why_great'   => 'The Docker for local LLMs. Run 8B and 70B parameter open-weights models on Apple Silicon with 1 command.',
                'stars'       => 115000,
                'featured'    => true,
                'sort_order'  => 16,
            ],
            [
                'title'       => 'searxng/searxng',
                'url'         => 'https://github.com/searxng/searxng',
                'description' => 'A privacy-respecting, open metasearch engine ideal for grounding AI search agents.',
                'category'    => 'Search & Grounding',
                'tags'        => ['search-engine', 'privacy', 'python', 'grounding'],
                'why_great'   => 'Gives autonomous agents unmetered, privacy-first web search capabilities without expensive SERP API quotas.',
                'stars'       => 17000,
                'featured'    => false,
                'sort_order'  => 17,
            ],
            [
                'title'       => 'BerriAI/litellm',
                'url'         => 'https://github.com/BerriAI/litellm',
                'description' => 'Call 100+ LLMs using the OpenAI Input/Output Format with proxy routing, fallbacks, and cost tracking.',
                'category'    => 'LLM Tooling',
                'tags'        => ['proxy', 'llm-router', 'python', 'cost-tracking'],
                'why_great'   => 'Unified interface for OpenAI, Anthropic, Gemini, Groq, and Bedrock with automatic fallback switching when an API is down.',
                'stars'       => 19500,
                'featured'    => true,
                'sort_order'  => 18,
            ],
            [
                'title'       => 'Significant-Gravitas/AutoGPT',
                'url'         => 'https://github.com/Significant-Gravitas/AutoGPT',
                'description' => 'The vision of accessible AI for everyone, to use and to build on.',
                'category'    => 'Agent Frameworks',
                'tags'        => ['autogpt', 'agents', 'autonomous'],
                'why_great'   => 'The pioneering repository that ignited the entire autonomous agent revolution in early 2023.',
                'stars'       => 168000,
                'featured'    => false,
                'sort_order'  => 19,
            ],
            [
                'title'       => 'browser-use/browser-use',
                'url'         => 'https://github.com/browser-use/browser-use',
                'description' => 'Make websites accessible for AI agents via Playwright and visual vision models.',
                'category'    => 'Agent Frameworks',
                'tags'        => ['browser-agent', 'playwright', 'vision'],
                'why_great'   => 'Enables agents to interact with modern complex SPAs, solve captchas, and execute browser workflows autonomously.',
                'stars'       => 31000,
                'featured'    => true,
                'sort_order'  => 20,
            ],
        ];

        foreach ($repos as $repo) {
            CuratedRepo::updateOrCreate(['url' => $repo['url']], $repo);
        }
    }
}
