<?php

return [
    // PDF & Document Tools
    [
        'name' => 'PDF Merge',
        'slug' => 'pdf-merge',
        'icon' => '📄',
        'description' => 'Merge multiple PDF files into one — fast, free, 100% browser-based. Your files never leave your device.',
        'keywords' => 'merge PDF online free, combine PDF files, PDF joiner, browser-based PDF merge',
        'category' => 'PDF & Document Tools',
        'category_slug' => 'pdf-document',
        'category_icon' => '📄',
    ],
    [
        'name' => 'PDF Split',
        'slug' => 'pdf-split',
        'icon' => '✂️',
        'description' => 'Split a large PDF file into multiple smaller documents easily. 100% free and online without any uploads.',
        'keywords' => 'split PDF online, extract PDF pages, PDF cutter, free online PDF tools',
        'category' => 'PDF & Document Tools',
        'category_slug' => 'pdf-document',
        'category_icon' => '📄',
    ],
    [
        'name' => 'PDF Compress',
        'slug' => 'pdf-compress',
        'icon' => '🗜️',
        'description' => 'Compress your PDF files to reduce size without losing quality. Works instantly in your browser.',
        'keywords' => 'compress PDF free, reduce PDF size, optimize PDF online, browser-based compression',
        'category' => 'PDF & Document Tools',
        'category_slug' => 'pdf-document',
        'category_icon' => '📄',
    ],
    [
        'name' => 'PDF to Image',
        'slug' => 'pdf-to-image',
        'icon' => '🖼️',
        'description' => 'Convert PDF pages into high-quality images (JPG/PNG). Fast, free, and completely secure.',
        'keywords' => 'PDF to JPG, PDF to PNG, convert PDF to image, online document converter',
        'category' => 'PDF & Document Tools',
        'category_slug' => 'pdf-document',
        'category_icon' => '📄',
    ],
    [
        'name' => 'Image to PDF',
        'slug' => 'image-to-pdf',
        'icon' => '📑',
        'description' => 'Combine multiple images into a single PDF document. Free, no watermarks, processed locally.',
        'keywords' => 'image to PDF converter, JPG to PDF, PNG to PDF, free browser tools',
        'category' => 'PDF & Document Tools',
        'category_slug' => 'pdf-document',
        'category_icon' => '📄',
    ],

    // Image Tools
    [
        'name' => 'Image Compressor',
        'slug' => 'image-compressor',
        'icon' => '📉',
        'description' => 'Compress JPG, PNG, and WebP images instantly in your browser to speed up your website.',
        'keywords' => 'image compressor online, compress image free, reduce image size, local image compression',
        'category' => 'Image Tools',
        'category_slug' => 'image',
        'category_icon' => '🖼️',
    ],
    [
        'name' => 'Image Resizer',
        'slug' => 'image-resizer',
        'icon' => '📏',
        'description' => 'Resize your images by pixel dimensions or percentages. Free, fast, and works without uploads.',
        'keywords' => 'image resizer online, resize photo free, change image dimensions',
        'category' => 'Image Tools',
        'category_slug' => 'image',
        'category_icon' => '🖼️',
    ],
    [
        'name' => 'Image Converter',
        'slug' => 'image-converter',
        'icon' => '🔄',
        'description' => 'Convert images between various formats effortlessly. 100% free online browser-based converter.',
        'keywords' => 'image format converter, free image conversion, convert photo online',
        'category' => 'Image Tools',
        'category_slug' => 'image',
        'category_icon' => '🖼️',
    ],
    [
        'name' => 'Image to WebP',
        'slug' => 'image-to-webp',
        'icon' => '🌐',
        'description' => 'Convert JPG, PNG, or GIF images to next-gen WebP format for optimal web performance.',
        'keywords' => 'convert to WebP online, JPG to WebP, PNG to WebP, free WebP converter',
        'category' => 'Image Tools',
        'category_slug' => 'image',
        'category_icon' => '🖼️',
    ],
    [
        'name' => 'PNG to JPG',
        'slug' => 'png-to-jpg',
        'icon' => '🔁',
        'description' => 'Convert PNG images with transparency to standard JPG files. Fast, secure, and fully local.',
        'keywords' => 'PNG to JPG converter, convert PNG to JPEG online, free browser tool',
        'category' => 'Image Tools',
        'category_slug' => 'image',
        'category_icon' => '🖼️',
    ],
    [
        'name' => 'JPG to PNG',
        'slug' => 'jpg-to-png',
        'icon' => '🔃',
        'description' => 'Convert standard JPG/JPEG photos into PNG format seamlessly right in your browser.',
        'keywords' => 'JPG to PNG converter, convert JPEG to PNG online, free image tools',
        'category' => 'Image Tools',
        'category_slug' => 'image',
        'category_icon' => '🖼️',
    ],

    // Developer Tools
    [
        'name' => 'JSON Formatter',
        'slug' => 'json-formatter',
        'icon' => '{}',
        'description' => 'Format, beautify, and validate JSON data online. A fast, free, no-upload tool for developers.',
        'keywords' => 'JSON formatter, JSON beautifier, validate JSON online, free developer tools',
        'category' => 'Developer Tools',
        'category_slug' => 'developer',
        'category_icon' => '💻',
    ],
    [
        'name' => 'JWT Decoder',
        'slug' => 'jwt-decoder',
        'icon' => '🔐',
        'description' => 'Decode JSON Web Tokens (JWT) safely in your browser. Verify claims and header data instantly.',
        'keywords' => 'JWT decoder online, decode JSON web token, JWT parser, browser-based JWT',
        'category' => 'Developer Tools',
        'category_slug' => 'developer',
        'category_icon' => '💻',
    ],
    [
        'name' => 'Regex Tester',
        'slug' => 'regex-tester',
        'icon' => '🔍',
        'description' => 'Test and debug your Regular Expressions instantly with real-time matching and syntax highlighting.',
        'keywords' => 'Regex tester online, regular expression evaluator, check regex match',
        'category' => 'Developer Tools',
        'category_slug' => 'developer',
        'category_icon' => '💻',
    ],
    [
        'name' => 'CSS Gradient Generator',
        'slug' => 'css-gradient-generator',
        'icon' => '🎨',
        'description' => 'Create beautiful linear and radial CSS gradients and instantly copy the CSS code.',
        'keywords' => 'CSS gradient generator, visual gradient builder, web design tools, CSS backgrounds',
        'category' => 'Developer Tools',
        'category_slug' => 'developer',
        'category_icon' => '💻',
    ],
    [
        'name' => 'Schema Generator',
        'slug' => 'schema-generator',
        'icon' => '🏗️',
        'description' => 'Generate rich snippets and JSON-LD structured data to boost your website\'s SEO performance.',
        'keywords' => 'JSON-LD schema generator, structured data maker, SEO rich snippets builder',
        'category' => 'Developer Tools',
        'category_slug' => 'developer',
        'category_icon' => '💻',
    ],
    [
        'name' => 'Base64 Encoder/Decoder',
        'slug' => 'base64-encoder-decoder',
        'icon' => '🔡',
        'description' => 'Easily encode text or files to Base64 format, or decode Base64 back to text strings locally.',
        'keywords' => 'Base64 encoder, Base64 decoder, encode decode strings online, developer utilities',
        'category' => 'Developer Tools',
        'category_slug' => 'developer',
        'category_icon' => '💻',
    ],

    // Calculator & Finance
    [
        'name' => 'QR Code Generator',
        'slug' => 'qr-code-generator',
        'icon' => '🔳',
        'description' => 'Create custom QR codes for URLs, text, Wi-Fi, and more. 100% free and instantly downloadable.',
        'keywords' => 'free QR code generator, make QR code online, URL to QR, custom QR code',
        'category' => 'Calculator & Finance',
        'category_slug' => 'calculator',
        'category_icon' => '🧮',
    ],
    [
        'name' => 'GST Calculator',
        'slug' => 'gst-calculator',
        'icon' => '📉',
        'description' => 'Calculate inclusive and exclusive Goods and Services Tax (GST) easily and precisely in seconds.',
        'keywords' => 'GST calculator online, tax calculator free, calculate GST amounts',
        'category' => 'Calculator & Finance',
        'category_slug' => 'calculator',
        'category_icon' => '🧮',
    ],
    [
        'name' => 'EMI Calculator',
        'slug' => 'emi-calculator',
        'icon' => '💳',
        'description' => 'Calculate your Equated Monthly Installment (EMI) for home, car, or personal loans instantly.',
        'keywords' => 'EMI calculator online, loan repayment calculator, mortgage calculator',
        'category' => 'Calculator & Finance',
        'category_slug' => 'calculator',
        'category_icon' => '🧮',
    ],
    [
        'name' => 'Age Calculator',
        'slug' => 'age-calculator',
        'icon' => '🎂',
        'description' => 'Calculate precise age in years, months, and days based on your date of birth instantly.',
        'keywords' => 'age calculator online, exact age finder, date of birth calculator',
        'category' => 'Calculator & Finance',
        'category_slug' => 'calculator',
        'category_icon' => '🧮',
    ],
    [
        'name' => 'Percentage Calculator',
        'slug' => 'percentage-calculator',
        'icon' => '💯',
        'description' => 'Easily calculate percentages, increases, decreases, and ratios for quick math on the go.',
        'keywords' => 'percentage calculator online, find percent increase, quick percentage math',
        'category' => 'Calculator & Finance',
        'category_slug' => 'calculator',
        'category_icon' => '🧮',
    ],
    [
        'name' => 'Unit Converter',
        'slug' => 'unit-converter',
        'icon' => '⚖️',
        'description' => 'Convert between various units of measurement including length, weight, volume, and temperature.',
        'keywords' => 'unit converter online, metric conversion tool, convert measurements free',
        'category' => 'Calculator & Finance',
        'category_slug' => 'calculator',
        'category_icon' => '🧮',
    ],

    // Productivity Tools
    [
        'name' => 'Word Counter',
        'slug' => 'word-counter',
        'icon' => '📝',
        'description' => 'Count words, characters, and sentences in your text instantly. Perfect for writers and students.',
        'keywords' => 'word counter online, character count tool, check word limit free',
        'category' => 'Productivity Tools',
        'category_slug' => 'productivity',
        'category_icon' => '⚡',
    ],
    [
        'name' => 'Password Generator',
        'slug' => 'password-generator',
        'icon' => '🔐',
        'description' => 'Generate strong, secure, and random passwords completely in your browser. No data transmitted.',
        'keywords' => 'strong password generator, secure random passwords, local password maker',
        'category' => 'Productivity Tools',
        'category_slug' => 'productivity',
        'category_icon' => '⚡',
    ],
    [
        'name' => 'Lorem Ipsum Generator',
        'slug' => 'lorem-ipsum-generator',
        'icon' => '📃',
        'description' => 'Generate custom Lorem Ipsum placeholder text for your designs, mockups, and development projects.',
        'keywords' => 'Lorem ipsum generator, placeholder text maker, dummy text online',
        'category' => 'Productivity Tools',
        'category_slug' => 'productivity',
        'category_icon' => '⚡',
    ],
    [
        'name' => 'Pomodoro Timer',
        'slug' => 'pomodoro-timer',
        'icon' => '⏱️',
        'description' => 'Boost your productivity with a free online Pomodoro timer. Focus blocks and scheduled breaks made simple.',
        'keywords' => 'Pomodoro timer online, focus timer free, productivity clock, study timer',
        'category' => 'Productivity Tools',
        'category_slug' => 'productivity',
        'category_icon' => '⚡',
    ],
    [
        'name' => 'Color Palette Generator',
        'slug' => 'color-palette-generator',
        'icon' => '🎨',
        'description' => 'Generate stunning color schemes and beautiful palettes for your next UI, web, or graphic design project.',
        'keywords' => 'color palette generator, UI color scheme maker, generate hex colors',
        'category' => 'Productivity Tools',
        'category_slug' => 'productivity',
        'category_icon' => '⚡',
    ],
];
